application:
    port: 8000
    hmac_secret: "some-long-secret-that-should-be-at-least-this-long-abcdefghijklmnopqrstuvwxyz"
database:
    host: "localhost"
    port: 5432
    username: "postgres"
    password: "password"
    database_name: "newsletter"
email_client:
    authorization_token: "my-secret-token"
    base_url: "http://localhost"
    sender_email: "admin@example.com"
    timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"